version: '3'

services:
  web:
    build: .
    container_name: neilwoodhouse_uk
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./static/:/APP/static:ro
      - ./templates/:/APP/templates:ro